name: 'Build package'
description: 'Build an Arch Linux package and run checks against it.'

inputs:
  package-dir:
    description: 'Package to build'
    required: true

outputs:
  result:
    description: 'The result of the checks that were run'
  failed:
    description: "Set to 'true' if the command results in a non-zero exit code, otherwise it will be 'false'"

runs:
  using: 'docker'
  image: 'ghcr.io/brenekh/auto-aur-build-package:latest'
  args:
    - ${{ inputs.package-dir }}
