name: 'Publish package'
description: 'Publish an Arch Linux package to the AUR.'

inputs:
  package-dir:
    description: 'Package to publish.'
    required: true
  ssh-private-key:
    description: 'Private key to use while publishing.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-dir }}
    - ${{ inputs.ssh-private-key }}
