name: "Identify Modified Package"
description: "Figure out which package has modifications and return it."

outputs:
  package:
    description: "The result of the search."
    value: ${{ steps.gh-script-find-modded-pkg.outputs.package }}

runs:
  using: "composite"
  steps:
    - name: Identify Modified Package
      uses: actions/github-script@v9
      id: gh-script-find-modded-pkg
      with:
        script: |
          const script = require('.github/actions/identify-modified-package/index.js')
          await script({core, github, context})
          try {
              if (context.eventName !== "pull_request" && context.eventName !== "pull_request_target") {
                  throw "Not a pull request";
              }

              const resp = await github.rest.pulls.listFiles({
                  ...context.repo,
                  pull_number: context.payload.pull_request?.number,
              })

              let moddedPackages = [];
              resp.data.forEach((file) => {
                  const splitFName = file.filename.split("/");
                  if (splitFName[0] === "pkgs") {
                      const splicedString = `${splitFName[0]}/${splitFName[1]}`;
                      if (moddedPackages.indexOf(splicedString) === -1) moddedPackages.push(splicedString)
                  }
              });

              if (moddedPackages.length > 1) {
                  throw "More than one modified package.";
              }

              console.log(moddedPackages);
              core.setOutput("package", moddedPackages[0]);

          } catch (error) {
              core.setFailed(error);
          }
