name: "Identify Modified Package"
description: "Figure out which package has modifications and return it."

outputs:
  package:
    description: "The result of the search."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7

    - name: Identify Modified Package
      uses: actions/github-script@v9
      with:
        script: |
          const script = require('.github/actions/identify-modified-package/index.js')
          console.log(script({core, github, context}))
