name: "Identify Modified Package"
description: "Figure out which package has modifications and return it."

inputs:
  github-token:
    description: "GitHub Token"
    required: true

outputs:
  package:
    description: "The result of the search."

runs:
  using: "node16"
  main: "lib/index.js"
