name: 'Identify Modified Package'
description: 'Figure out which package has modifications and return it.'

outputs:
  package:
    description: 'The result of the search.'

runs:
  using: 'node12'
  main: 'lib/index.js'
