name: "Identify Modified Package"
description: "Figure out which package has modifications and return it."

outputs:
  package:
    description: "The result of the search."
    value: ${{ steps.gh-script-find-modded-pkg.outputs.package }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7

    - name: Identify Modified Package
      uses: actions/github-script@v9
      id: gh-script-find-modded-pkg
      with:
        script: |
          const script = require('.github/actions/identify-modified-package/index.js')
          script({core, github, context})
