name: Automatically Update Package Versions

on:
  # schedule:
  #   - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update packages
        uses: ./.github/actions/update-package-via-manifest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
