name: Build on PR Update

on:
  pull_request_target: # We need pull_request_target so we have access to the repository's secrets.
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR. This is only safe because we require approval for every outside PR.

      - name: Identify modified package
        id: modded-pkg
        uses: ./.github/actions/identify-modified-package
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        id: build-package
        uses: ./.github/actions/build-package
        with:
          package-dir: ${{ steps.modded-pkg.outputs.package }}

      - name: Test package
        id: test-package
        uses: ./.github/actions/test-package
        with:
          package-dir: ${{ steps.modded-pkg.outputs.package }}

      - name: Hide previous build results
        uses: int128/hide-comment-action@v1
        if: always()
        with:
          starts-with: <!-- Build Results Comment -->

      # Send build results to PR as a comment
      - name: Comment build results
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "<!-- Build Results Comment -->\n${{ steps.build-package.outputs.result }}" + "${{ steps.test-package.outputs.result }}" + "\n\nSee logs for more details"
            })

      # TODO: Fail build if makepkg, pacman, or testCmd fail (will need extra output from buildpkg.py)
