name: Build on PR Update

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # TODO: Identify which package was updated, and error out if more than was modified

      - name: Build package
        id: build-package
        uses: ./.github/actions/build-package
        with:
          package-dir: 'pkgs/beryl'

      - name: Echo output
        run: echo "${{ steps.build-package.outputs.result }}"

      # TODO: Send build results to PR as a comment

  # publish-beryl:
  #   runs-on: [self-hosted]

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Publish package
  #       uses: ./.github/actions/publish-package
  #       with:
  #         package-dir: 'pkgs/beryl'
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
