name: Build on PR Update

on: push

jobs:
  build-beryl:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build package
        uses: ./.github/actions/build-package
        with:
          package-dir: 'pkgs/beryl'

      - name: Publish package
        uses: ./.github/actions/publish-package
