name: Build on PR Update

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Identify modified package
        id: modded-pkg
        uses: ./.github/actions/identify-modified-package
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        id: build-package
        uses: ./.github/actions/build-package
        with:
          package-dir: ${{ steps.modded-pkg.outputs.package }}

      - name: Echo output
        run: echo "${{ steps.build-package.outputs.result }}"

      # Send build results to PR as a comment
      - name: Comment build results
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.build-package.outputs.result }}"
            })

      # TODO: Fail build if makepkg, pacman, or testCmd fail (will need extra output from buildpkg.py)
