name: Publish on PR Accept

on:
  pull_request:
   types: [labeled]

jobs:
  output:
    runs-on: [self-hosted]
    if: github.event.label.name == 'lgtm'

    steps:
      - run: cat $GITHUB_EVENT_PATH
