name: Publish on PR Accept

on:
  pull_request:
   types: [labeled]

jobs:
  publish:
    runs-on: [self-hosted]
    if: github.event.label.name == 'lgtm'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Identify modified package
        id: modded-pkg
        uses: ./.github/actions/identify-modified-package
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to AUR
        uses: ./.github/actions/publish-package
        with:
          package-dir: ${{ steps.modded-pkg.outputs.package }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Comment on PR (Success)
        uses: actions/github-script@v4
        if: ${{ success() }}
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Successfully uploaded new data for '${{ steps.modded-pkg.outputs.package }}' to the AUR."
            })

      - name: Comment on PR (Failure)
        uses: actions/github-script@v4
        if: ${{ failure() }}
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Could not upload to the AUR. Check out [the Actions log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details."
            })

      - name: Merge PR
        run: echo "Hi"
