name: Publish on PR Accept

on:
  pull_request:
   types: [labeled]

jobs:
  publish:
    runs-on: [self-hosted]
    if: github.event.label.name == 'lgtm'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Identify modified package
        id: modded-pkg
        uses: ./.github/actions/identify-modified-package
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to AUR
        uses: ./.github/actions/publish-package
        with:
          package-dir: ${{ steps.modded-pkg.outputs.package }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Comment on PR
        run: echo "Hi"

      - name: Close PR
        run: echo "Hi"
